/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */

#include "s3eExt.h"
#include "IwDebug.h"
#include "s3eDevice.h"


#include "ExtFyber.h"


// Define S3E_EXT_SKIP_LOADER_CALL_LOCK on the user-side to skip LoaderCallStart/LoaderCallDone()-entry.
// e.g. in s3eNUI this is used for generic user-side IwUI-based implementation.
#ifndef S3E_EXT_SKIP_LOADER_CALL_LOCK
#if (defined(WINAPI_FAMILY) && (WINAPI_FAMILY == WINAPI_FAMILY_PHONE_APP)) || defined I3D_ARCH_NACLX86_64
// For platforms missing stack-switching (WP8, NaCl, etc.) make loader-entry via LoaderCallStart/LoaderCallDone() on the user-side.
#define LOADER_CALL_LOCK
#endif
#endif


#include "ExtFyber_interface.h"

static ExtFyberFuncs g_Ext;
static bool g_GotExt = false;
static bool g_TriedExt = false;
static bool g_TriedNoMsgExt = false;

static bool _extLoad()
{
    if (!g_GotExt && !g_TriedExt)
    {
        s3eResult res = s3eExtGetHash(0xdd08f5ce, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        else
            s3eDebugAssertShow(S3E_MESSAGE_CONTINUE_STOP_IGNORE,                 "error loading extension: ExtFyber");

        g_TriedExt = true;
        g_TriedNoMsgExt = true;
    }

    return g_GotExt;
}

static bool _extLoadNoMsg()
{
    if (!g_GotExt && !g_TriedNoMsgExt)
    {
        s3eResult res = s3eExtGetHash(0xdd08f5ce, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        g_TriedNoMsgExt = true;
        if (g_TriedExt)
            g_TriedExt = true;
    }

    return g_GotExt;
}

s3eBool ExtFyberAvailable()
{
    _extLoadNoMsg();
    return g_GotExt ? S3E_TRUE : S3E_FALSE;
}

s3eResult ExtFyberRegister(ExtFyberCallback cbid, s3eCallback fn, void* userData)
{
    IwTrace(EXTFYBER_VERBOSE, ("calling ExtFyber[0] func: ExtFyberRegister"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_ExtFyberRegister);
#endif

    s3eResult ret = g_Ext.m_ExtFyberRegister(cbid, fn, userData);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_ExtFyberRegister);
#endif

    return ret;
}

s3eResult ExtFyberUnRegister(ExtFyberCallback cbid, s3eCallback fn)
{
    IwTrace(EXTFYBER_VERBOSE, ("calling ExtFyber[1] func: ExtFyberUnRegister"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_ExtFyberUnRegister);
#endif

    s3eResult ret = g_Ext.m_ExtFyberUnRegister(cbid, fn);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_ExtFyberUnRegister);
#endif

    return ret;
}

void fyber_marmalade_setup(const char* appId, const char* securityToken, const char* userId, const char* bucketId, const char* conditionGroupId, ExtFyberStatusCallbackFn fn)
{
    IwTrace(EXTFYBER_VERBOSE, ("calling ExtFyber[2] func: fyber_marmalade_setup"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_fyber_marmalade_setup);
#endif

    g_Ext.m_fyber_marmalade_setup(appId, securityToken, userId, bucketId, conditionGroupId, fn);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_fyber_marmalade_setup);
#endif

    return;
}

void requestOffers()
{
    IwTrace(EXTFYBER_VERBOSE, ("calling ExtFyber[3] func: requestOffers"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_requestOffers);
#endif

    g_Ext.m_requestOffers();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_requestOffers);
#endif

    return;
}

int showAd()
{
    IwTrace(EXTFYBER_VERBOSE, ("calling ExtFyber[4] func: showAd"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_showAd);
#endif

    int ret = g_Ext.m_showAd();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_showAd);
#endif

    return ret;
}

void fyber_cache_pause_download()
{
    IwTrace(EXTFYBER_VERBOSE, ("calling ExtFyber[5] func: fyber_cache_pause_download"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_fyber_cache_pause_download);
#endif

    g_Ext.m_fyber_cache_pause_download();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_fyber_cache_pause_download);
#endif

    return;
}

void fyber_cache_resume_download()
{
    IwTrace(EXTFYBER_VERBOSE, ("calling ExtFyber[6] func: fyber_cache_resume_download"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_fyber_cache_resume_download);
#endif

    g_Ext.m_fyber_cache_resume_download();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_fyber_cache_resume_download);
#endif

    return;
}
