/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef EXTFYBER_AUTODEFS_H
#define EXTFYBER_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_EXTFYBER_NAME "ExtFyber"
#define S3E_EXT_EXTFYBER_HASH 0xdd08f5ce

#ifdef S3E_EXT_REGISTER
#ifndef S3E_EXT_REGISTER_KEY
#define S3E_EXT_REGISTER_KEY(name, num, key) S3E_EXT_REGISTER(name, num)
#endif
S3E_EXT_REGISTER("ExtFyber", 7)
#else

#endif /* S3E_EXT_REGISTER */
#endif /* !EXTFYBER_AUTODEFS_H */
